### ISSUE TITLE
error: use of undeclared identifier 'YoloV5Focus_layer_creator'

### ISSUE THREAD

**Issue by randauto** [FeiGeChuanShu/ncnn-android-yolov6#1]
![error_build](https://user-images.githubusercontent.com/6858507/175505638-e5368679-f360-459a-b0ef-a3075a973773.png)
I found this error when I build it. Please help me. Correct from step 1 & 2.

**Comment by FeiGeChuanShu** [comment]
@randauto 删掉即可 focus没用到

**Comment by randauto** [comment]
> 

Thanks! Closed.
